#!/bin/bash
WDIR=$HOME/regionh/Dalux_RPA
cd $WDIR

LASTINDEX=$(tail -1 EAN_PSP.log | awk '{print $4}' | tr -d ",")
MODES=$(cat modes.txt | tail -1)
python3.10 -u src/main.py $(($LASTINDEX+1)) "$(echo $MODES | tr -d '\\')" > run.log
